Resources/Prototypes/Roles/Jobs/Civilian/clown.yml, Resources/Prototypes/Roles/Jobs/Civilian/mime.yml
Изменено время на роли клоуна и мима с 1500 минут на 120 (2 часа).
**Медиа**
Не требуется
**Проверки**
**Изменения**
:cl:KTDR
- tweak: Изменено необходимое время на роли клоуна и мима.
=> Tweaked time for clown and mime roles

Resources/Prototypes/Entities/Structures/Furniture/dresser.yml
Исправляет ошибку из-за которой в комодах не появлялись вещи глав.
**Медиа**
**Проверки**
**Изменения**
:cl:gitdubses
- fix: Исправлена ошибка с комодами
=> bugfix dresser

Resources/Maps/Radium/Ruins/MSS.yml, Resources/Maps/Radium/Ruins/ultra-storage.yml
Срочный фикс шлюзов на новых обломках. Теперь их не смогут открывать монстры. + Исправлено питание на МКС.
**Медиа**
Не требуется
**Проверки**
**Изменения**
:cl:KTDR
- fix: Исправлены шлюзы на новых обломках.
- fix: Исправлено питание от СМЭСа на МКС.
=> Fix new wrecks

Resources/Prototypes/Radium/Chemicals/reagents.yml
Изменяет и исправляет реагенты, а также их обновляет
**Медиа**
Не требуется
**Проверки**
**Изменения**
:cl:gitdubses
- tweak: Изменён лечащий урон
- tweak: Изменены группы у реагентов
- fix: Исправлена ошибка из-за которой, синтплоть только лечила burn
- add: Добавлен лечащий урон при приёме внутрь у реагентов: cульфадиазин серебра, кровоостанавливающая пудра
=> Reagents buff & Fix bug & Reagents update

Resources/Prototypes/Entities/Mobs/NPCs/space.yml
Изменение пауков обломков, теперь они не впрыскивают хлоральгидрат.
**Медиа**
Не требуется
**Проверки**
**Изменения**
:cl:KTDR
- remove: Убрано усыпление у космических пауков
=> Fix space spiders

Resources/Prototypes/Backmen/Entities/Objects/Specific/chemistry.yml, Resources/Prototypes/Entities/Objects/Specific/chemistry.yml
Изменяет объем с слотов на вместимость, а также добавление вайтлиста для обычной баночки с таблетками.
Блюспейс таблетница теперь имеет старую систему инвентаря
**Медиа**
Не требуется
**Проверки**
**Изменения**
:cl:gitdubses
- fix: Исправлена ошибка из-за которой не получалось создавать таблетки в хим мастере 4000
=> fix pill canister

Resources/Prototypes/Radium/Chemicals/reagents.yml
Изменены группы реагентов. Добавлен баланс для перфтордекалина.
**Медиа**
Не требуется
**Проверки**
**Изменения**
:cl:gitdubses
- tweak: Изменены группы для реагентов
- add: Добавлен баланс для перфтордекалина
=> reagents update and balance

Resources/Prototypes/Entities/Mobs/NPCs/argocyte.yml
Добавляет способности Аргоцитам для PvP и PvE ивентов
**Медиа**
**Проверки**
**Изменения**
:cl:
- add: Добавлена способность рожать большим бабайкам
- add: Добавлена способность инвиза личинкам
=> Argocyte revork

Resources/Locale/ru-RU/ss14-ru/prototypes/catalog/fills/firstaidkits.ftl, Resources/Prototypes/Radium/Catalog/Cargo/cargo-engineering.yml, Resources/Prototypes/Radium/Catalog/Cargo/cargo_medical.yml, Resources/Prototypes/Radium/Catalog/Cargo/cargo_service.yml, Resources/Prototypes/Radium/Catalog/Fills/Items/firstaidkits.yml
Добавляет в каталог: РИТЭГ, АлкоМат, аптечка с медипенами. (по поводу цен вопросы к фризу)
**Медиа**
**Проверки**
**Изменения**
:cl:KTDR
- tweak: Изменён каталог карго
=> Add new items for buy in cargo

Resources/Prototypes/Radium/Hydroponics/seeds.yml
Убирает у мунлина harvest repeat.
**Медиа**
Не требуется
**Проверки**
**Изменения**
:cl: gitdubses
- remove: Убран harvest repeat у мунлина
=> moonlin harvest repeat remove

Resources/Prototypes/Radium/Entities/Objects/Consumable/Food/produce.yml, Resources/Prototypes/Radium/Hydroponics/seeds.yml
Фиксит баланс и яркость мунлина.
**Медиа**
**Проверки**
**Изменения**
:cl: gitdubses
- fix: Исправлен баланс
- tweak: Изменён радиус и яркость мунлина
=> botanica fix balance

Resources/Locale/ru-RU/radium/prototypes/entities/objects/consumable/food/produce.ftl, Resources/Prototypes/Radium/Entities/Objects/Consumable/Food/produce.yml
Исправляет ошибку в названии, и описании взрывного лимона, и добавляет для produce свои fluent файлы.
**Медиа**
Не требуется
**Проверки**
**Изменения**
:cl: gitdubses
- add: Добавлены для produce fluent файлы
- fix: Исправлена орфографическая ошибка в название, и описании взрывного лимона
=> ftl fix produce

Resources/Prototypes/Catalog/uplink_catalog.yml, Resources/Prototypes/Radium/Catalog/uplink_calatog.yml
Переносит в аплинке пакет семян взрывных лимонов, в папку радиума, и уменьшает стоимость пакет семян взрывных лимонов на 1 TK.
**Медиа**
Не требуется
**Проверки**
**Изменения**
:cl: gitdubses
- remove: Убран в аплинке пакет семян взрывных лимонов из папки оффов
- tweak: Изменена цена взрывных лимонов с 5 TK до 4 TK
=> uplink catalog radium

Resources/Prototypes/Radium/Hydroponics/seeds.yml
Балансит реплика-под, и добавляет harvest repeat к реплика-поду
**Медиа**
Не требуется
**Проверки**
**Изменения**
:cl: gitdubses
- add: Добавлен harvestRepeat к реплика-поду и к клоуна-поду
- remove: Убран idealLight у реплика-пода и у клоун-пода
- tweak: Изменён potency у реплика-под с 5 до 3, maturation с 7 до 6
- tweak: Изменён potency у клоуна-под с 5 до 2, maturation с 7 до 5, production с 3 до 4, lifespan c 50 до 45
=> replica pod balance

Resources/Prototypes/Radium/Entities/Objects/Fun/maxwell.yml
Теперь maxwell играет всегда свою песенку
**Медиа**
Не требуется
**Проверки**
**Изменения**
:cl: gitdubses
- add: Добавлена возможность проигрывать maxwell свою музыку на постоянной основе
=> now maxwell can play his music

Resources/Prototypes/Catalog/Fills/Lockers/cargo.yml, Resources/Prototypes/Hydroponics/seeds.yml
Из-за конфликтов пропал новый контент радиума, этот пр всё возвращает
**Медиа**
Не требуется
**Проверки**
**Изменения**
:cl: gitdubses
- add: Добавлен новый контент радиума
=> return new content

Resources/Prototypes/Radium/Hydroponics/seeds.yml
Балансит реплика поды, что не позволяет слишком абузить ими.
**Медиа**
Не требутся
**Проверки**
**Изменения**
:cl: gitdubses
- tweak: Изменён баланс реплика под и клоун пода
=> rebalance replicapod

Resources/Prototypes/Entities/Objects/Specific/Medical/healthanalyzer.yml
Теперь анализатор не выделяется на общем фоне
**Медиа**
**Проверки**
**Изменения**
:cl: gitdubses
- remove: Убрано unshaded у анализатора
=> unshader remove

Resources/Prototypes/Catalog/Fills/Lockers/cargo.yml
Возвращает автоинъектор выживания в шкафчик утилизатора.
**Медиа**
Не требуется
**Проверки**
**Изменения**
:cl: gitdubses
- add: Добавлен автоинъектор в шкафчик утилизатора
=> return medipen

.github/workflows/labeler-radium.yml
Этикировщик для вики.
**Медиа**
Не требуется.
**Проверки**
**Изменения**
:cl: gitdubses
- add: Добавлен этикировщик для вики
=> labeler wiki

.github/labeler.yml
Добавляет новые этикетки для пр-ов.
**Медиа**
Не требуется
**Проверки**
**Изменения**
:cl: gitdubses
- add: Добавлены этикетки
=> Labeler update

Resources/Prototypes/Entities/Objects/Specific/Chapel/bibles.yml
Было добавлено свечение от библии
**Медиа**
**Проверки**
**Изменения**
- add: Добавлено свечение от библии
=> Glowing bible

Resources/Prototypes/Entities/Objects/Misc/briefcases.yml
Был добавлен урон от чемоданов
**Медиа**
Не требуется
**Проверки**
**Изменения**
:cl:
- add: Добавлен урон от чемоданов в 5 единиц тупого урона
=> damage for briefcase

Resources/Prototypes/Recipes/Construction/clothing.yml, Resources/Prototypes/Recipes/Construction/furniture.yml, Resources/Prototypes/Recipes/Construction/storage.yml, Resources/Prototypes/Recipes/Construction/structures.yml, Resources/Prototypes/Recipes/Crafting/bots.yml, Resources/Prototypes/Recipes/Crafting/smokeables.yml
Локализация g меню
**Медиа**
Не требуется
**Проверки**
**Изменения**
:cl: gitdubses
- add: Добавлена локализация g menu
=> localization g menu update

Content.Client/HealthAnalyzer/UI/HealthAnalyzerWindow.xaml.cs
**Медиа**
**Проверки**
**Изменения**
:cl: Xo6a
- add: -
- remove: -
- tweak: -
- fix: Теперь графический интерфейс анализатора здоровья работает нормально!
=> now health analyzer locale is doing it's job. yay!

Resources/Locale/ru-RU/backmen/prototypes/entities/structures/storage/closets/fills.ftl, Resources/Locale/ru-RU/backmen/psionics/death-gasp.ftl, Resources/Prototypes/_Backmen/Recipes/Construction/Graphs/structures/glimmerdevices.yml
Устраняет некоторые ошибки перевода, присущие контенту бакмэна. В первую очередь, меняет описание рецепта сияющего стока. Вместо блюспейс кристаллов, указаны кристаллы нормальности
**Медиа**
Ниже представлена текущая версия рецепта
**Проверки**
**Изменения**
:cl:
- fix: Исправлены файлы локализации
=> Небольшие исправления локализации.

Resources/Prototypes/Corvax/Entities/Mobs/Customization/Markings/cat_parts.yml, Resources/Prototypes/Corvax/Entities/Mobs/Customization/Markings/fox_parts.yml, Resources/Prototypes/Corvax/Entities/Mobs/Customization/Markings/slime_cat_parts.yml, Resources/Prototypes/Corvax/Entities/Mobs/Customization/Markings/slime_fox_parts.yml, Resources/Prototypes/Entities/Mobs/Customization/Markings/cat_parts.yml, Resources/Prototypes/Entities/Mobs/Customization/Markings/cyberlibs.yml, Resources/Prototypes/Entities/Mobs/Customization/Markings/gauze.yml, Resources/Prototypes/Entities/Mobs/Customization/Markings/human_noses.yml, Resources/Prototypes/_Backmen/Entities/Mobs/Customization/Markings/tails.yml
Разблокирует многие черты внешности, такие как протезы, кошачьи уши и хвосты. Добавляет черты для некоторых рас, в частности, добавляет протезы для слаймолюдов, арахн. Добавляет шрамы для лис и арахн. Добавляет татуировки для арахн. Добавляет арахнам косметические бинты . Добавляет людям акулий хвост(sharkgirlsupremacy)
**Медиа**
**Проверки**
**Изменения**
:cl:
- tweak: Изменены ограничения по чертам внешности
=> Sponsor's stuff unblock

Resources/Prototypes/Entities/Mobs/Customization/Markings/scars.yml, Resources/Prototypes/Entities/Mobs/Customization/Markings/tattoos.yml, Resources/Prototypes/_Backmen/Entities/Mobs/Species/arachne.yml, Resources/Prototypes/_Backmen/Species/arachne.yml
Удаляет модификатор урона арахн, который ломал использование наборов медикаментов.
Добавляет арахнам больше косметических предметов.
Изменяет арахн как игровую расу.
**Медиа**
**Проверки**
**Изменения**
:cl:
- tweak: Изменены арахны классические для большего соответствия игровым реалиям.
- tweak: Арахнам доступно больше косметических предметов
=> The rebuild of arachne

Content.Client/Radium/Changeling/ChangelingSystem.cs, Content.Server/Medical/DefibrillatorSystem.cs, Content.Server/Radium/Changeling/EntitySystems/ChangelingSystem.Abilities.cs, Content.Server/Radium/Changeling/EntitySystems/ChangelingSystem.cs, Content.Shared/Radium/Changeling/Components/ChangelingComponent.cs, Resources/Locale/ru-RU/radium/roles/changeling/changeling.ftl, Resources/Prototypes/Actions/polymorph.yml, Resources/Prototypes/Radium/Actions/types.yml, Resources/Prototypes/Radium/StatusIcon/antag.yml
Исправляет ошибки в действиях. Добавляет иконку фракции.
=> Changeling final fix

Content.Server/Radium/Changeling/StationEvents/ChangelingRule.cs, Resources/Prototypes/game_presets.yml
Добавляет выживанию минимальное количество игроков.
=> Fix secret

Resources/Prototypes/Radium/Entities/Mobs/Player/slugcat.yml
Теперь слизнекоты могут подбирать предметы! (добавлен компонент ComplexInteraction)
Слизнекися теперь подобно человеку, только оно меньше...
Change requested by PIVOZAVR (@rianna4444 / rofls.pon)
**Медиа**
**Проверки**
**Изменения**
:cl: Xo6a
- add: -
- remove: -
- tweak: теперь слизнекоты могут поднимать и использовать предметы!
- fix: -
=> Slugcat fix

Resources/Locale/ru-RU/backmen/store/vampire.ftl
Изменяет описание способностей вампира внутри магазина эволюции. Изменяет формулировку и закрывает грамматические ошибки уровня шестого класса.(You have 5 attemts to spell "пробежка" correctly)
**Медиа**
Отсутствует.
|
**Проверки**
**Изменения**
:cl:
- fix: Исправлено описание способностей вампира.
=> Vampire translations fixes

Resources/Prototypes/_Backmen/Entities/Mobs/Species/felinid.yml
Увеличивает фелинидов до размеров человека. Удаляет фелинидам возможность незаметно воровать. Увеличивает хитбокс, уменьшает выносливость на 10 ед.
**Медиа**
**Проверки**
**Изменения**
:cl:
- tweak: Фелиниды больше не могут скрытно воровать.
- tweak: Изменён размер фелинидов
- tweak: Уменьшена выносливость фелинидов
- tweak: Изменены значения рукопашного урона фелинидов
- tweak: Фелиниды дольше восстанавливаются от асфексии
=> Felinid rabalance

Resources/Locale/ru-RU/corvax/paper/doc-printer.ftl
Удаляет логотип НТ из стандартных форм принтера документов.
Зачем я это сделал?
Он не работает так, как должен.
**Изменения**
=> NT logo "fix"
